### ISSUE TITLE
event Branch Describing how I use fontional companents.

### ISSUE THREAD

**Issue by otmanTR** [otmanTR/math-magicians#4]
In this project, I used the useState hook.

'function Calculator() {
  const [state, setState] = useState({ total: 0, next: null, operation: null });

  const { total, next, operation } = state;

  const calculateResult = (calculateButton) => {
    setState((state) => calculate(state, calculateButton.target.textContent));
  };'

In this function, the useState hook defined the objects of total, next, and operation as the initial values of the state. With this, I used these objects in my calculation function.

**Comment by julie-ify** [comment]
Hi @otmanTR,

## Highlights!
- Good explanation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
